// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9zK4Gwrizc11d59XoSfCw9E0fAuT3BY',
    appId: '1:873554694706:web:a40e3ee985e5071afe222b',
    messagingSenderId: '873554694706',
    projectId: 'planalert',
    authDomain: 'planalert.firebaseapp.com',
    storageBucket: 'planalert.firebasestorage.app',
    measurementId: 'G-7D13TZZX32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfaW9VT2cYcgN54Qo6tPlpUPb2ovValY',
    appId: '1:873554694706:android:a6f43c9d906c43f9fe222b',
    messagingSenderId: '873554694706',
    projectId: 'planalert',
    storageBucket: 'planalert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSXt7KKx8QC7wbxM9MvIxV2PJl2zxUcb8',
    appId: '1:873554694706:ios:e519747fe31d7286fe222b',
    messagingSenderId: '873554694706',
    projectId: 'planalert',
    storageBucket: 'planalert.firebasestorage.app',
    iosBundleId: 'com.example.planAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSXt7KKx8QC7wbxM9MvIxV2PJl2zxUcb8',
    appId: '1:873554694706:ios:e519747fe31d7286fe222b',
    messagingSenderId: '873554694706',
    projectId: 'planalert',
    storageBucket: 'planalert.firebasestorage.app',
    iosBundleId: 'com.example.planAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz9zK4Gwrizc11d59XoSfCw9E0fAuT3BY',
    appId: '1:873554694706:web:d8fd46f76b36475bfe222b',
    messagingSenderId: '873554694706',
    projectId: 'planalert',
    authDomain: 'planalert.firebaseapp.com',
    storageBucket: 'planalert.firebasestorage.app',
    measurementId: 'G-WV707398SK',
  );
}
